"""Game protocol used by the CFR+ solver.

Games expose a tree with three node kinds: chance, decision (per player),
and terminal. State objects are immutable so the solver can recurse
without copying.
"""

from __future__ import annotations

from typing import Any, Hashable, Protocol, runtime_checkable


@runtime_checkable
class Game(Protocol):
    num_players: int

    def initial_state(self) -> Any: ...
    def is_terminal(self, state: Any) -> bool: ...
    def is_chance(self, state: Any) -> bool: ...
    def chance_outcomes(self, state: Any) -> list[tuple[Any, float]]: ...
    def apply_chance(self, state: Any, outcome: Any) -> Any: ...
    def current_player(self, state: Any) -> int: ...
    def legal_actions(self, state: Any) -> list[Any]: ...
    def apply(self, state: Any, action: Any) -> Any: ...
    def utility(self, state: Any, player: int) -> float: ...
    def infoset_key(self, state: Any, player: int) -> Hashable: ...
